### ISSUE TITLE
[pytket-qiskit] Not working with latest version

### ISSUE THREAD

**Issue by quosta** [CQCL/pytket-extensions#277]
The package is not working with qiskit 0.34.1
If this requirement is ignored upon installation the import will raise an error:
```
from pytket.extensions.qiskit import IBMQBackend
Traceback (most recent call last):

  Input In [80] in <module>
    from pytket.extensions.qiskit import IBMQBackend

  File /usr/lib/python3.10/site-packages/pytket/extensions/qiskit/__init__.py:18 in <module>
    from .backends import (

  File /usr/lib/python3.10/site-packages/pytket/extensions/qiskit/backends/__init__.py:16 in <module>
    from .ibm import IBMQBackend, NoIBMQAccountError

  File /usr/lib/python3.10/site-packages/pytket/extensions/qiskit/backends/ibm.py:47 in <module>
    from pytket.extensions.qiskit.qiskit_convert import (

  File /usr/lib/python3.10/site-packages/pytket/extensions/qiskit/qiskit_convert.py:139 in <module>
    Gate: OpType.Custom,

AttributeError: type object 'pytket._tket.circuit.OpType' has no attribute 'Custom'
```

**Comment by quosta** [comment]
I can confirm that it is working, thank you!
